#!/usr/bin/env node
// Generate a PR comment showing where new/modified chronicles land in the tree.
// Reads changed files from `git diff --name-only --diff-filter=AM <base>...HEAD`,
// or env CHANGED_FILES (newline separated). Emits markdown to stdout.
//
// Used by .github/workflows/chronicle-pr-tree.yml

import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { dirname, join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..');
const BUILD = join(__dirname, 'build-tree.js');

function changedFiles() {
  if (process.env.CHANGED_FILES) {
    return process.env.CHANGED_FILES.split('\n').filter(Boolean);
  }
  const base = process.env.BASE_REF || 'origin/main';
  try {
    const out = execFileSync('git', ['diff', '--name-only', '--diff-filter=AM', `${base}...HEAD`], { encoding: 'utf8' });
    return out.split('\n').filter(Boolean);
  } catch {
    return [];
  }
}

const skipNames = new Set(['index.md', 'log.md', 'AGENTS.md', 'README.md']);
const changed = changedFiles().filter(f =>
  f.startsWith('chronicles/') &&
  f.endsWith('.md') &&
  !skipNames.has(basename(f))
);

if (!changed.length) {
  console.log('<!-- no chronicle changes -->');
  process.exit(0);
}

const items = [];
for (const f of changed) {
  let raw; try { raw = readFileSync(join(REPO_ROOT, f), 'utf8'); } catch { continue; }
  let parsed; try { parsed = matter(raw); } catch { continue; }
  const fm = parsed.data || {};
  if (!fm.id) continue;
  const titleMatch = parsed.content.match(/^#\s+(.+)$/m);
  items.push({
    file: f,
    id: fm.id,
    title: titleMatch ? titleMatch[1].trim() : basename(f, '.md'),
    type: fm.type,
    team: fm.team,
    tags: fm.tags || [],
    scope: fm.scope || {},
    confidence: fm.confidence
  });
}

if (!items.length) {
  console.log('<!-- changed files have no chronicle frontmatter -->');
  process.exit(0);
}

const headSha = process.env.HEAD_SHA || 'HEAD';
const lines = [];
lines.push('## 📚 Chronicle changes in this PR');
lines.push('');
lines.push(`This PR adds or updates **${items.length}** chronicle atom${items.length === 1 ? '' : 's'}. Tree shown below with the new node${items.length === 1 ? '' : 's'} highlighted.`);
lines.push('');

lines.push('| Chronicle | Type | Team | Tags | Scope |');
lines.push('|-----------|------|------|------|-------|');
for (const it of items) {
  const scopeStr = [
    it.scope.teams?.length ? `teams: ${it.scope.teams.join(',')}` : null,
    it.scope.repos?.length ? `repos: ${it.scope.repos.join(',')}` : null,
    it.scope.paths?.length ? `paths: ${it.scope.paths.join(',')}` : null
  ].filter(Boolean).join(' / ') || 'all';
  lines.push(`| [\`${it.id}\`](../blob/${headSha}/${it.file}) ${it.title} | ${it.type || '?'} | ${it.team || '?'} | ${it.tags.join(', ')} | ${scopeStr} |`);
}
lines.push('');

for (const it of items) {
  const mermaid = execFileSync('node', [BUILD, '--mermaid', '--highlight', it.id], { encoding: 'utf8' });
  lines.push('<details>');
  lines.push(`<summary><b>Where <code>${it.id}</code> lands</b> — ${it.title}</summary>`);
  lines.push('');
  lines.push(mermaid.trim());
  lines.push('');
  lines.push('</details>');
  lines.push('');
}

lines.push('---');
lines.push('<sub>Auto-generated by `scripts/pr-comment.js`. Click any node to open the chronicle.</sub>');

process.stdout.write(lines.join('\n') + '\n');
